---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data: 
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_DATABASE: "cities"
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
    tier: db
spec:
  containers:
  - name: mysql
    imagePullPolicy: Always
    image: bharattarun/mysql:v1
    envFrom:
    - configMapRef:
        name: mysql-config 
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
    ports:
     - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    name: mysql 
    tier: db
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3306