apiVersion: v1
kind: Pod
metadata: 
  name: configmap-pod
specs:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: corse
      valueFrom:
        configMapKeyRef:
          name: course-config
          key: course
    - name: duration
      valueFrom:
        configMapKeyRef:
          name: course-config
          key: duration