apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels: #these labels are related to replicaset resource
    app: nginx
    tier: frontend
spec: # modify replicas according to the scenario
  replicas: 3
  selector:
    matchLabels: #this is the syntax replicaset use to find which pod should be scaled and maintained
      tier: frontend
  template: #pod template , labels are related to pod
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx